exp_name: dqn-CartPole-v1
seed: 31415
track: true
wandb_project_name: JAXRL-baselines
wandb_entity: sustech-emi-org
capture_video: false
save_model: false
upload_model: false
hf_entity: ''
agent: dqn
env_id: CartPole-v1
total_timesteps: 500000
learning_rate: 0.00025
num_envs: 1
buffer_size: 10000
gamma: 0.99
tau: 1.0
target_network_frequency: 500
batch_size: 128
start_e: 1.0
end_e: 0.05
exploration_fraction: 0.5
learning_starts: 10000
train_frequency: 10

random seed=42
[2024-05-22 15:47:17,023][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0ba0944490>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:17,024][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0ba0944c10>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:17,025][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0ba0944b50>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:17,027][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0ba0946c20>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:17,027][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0ba0946da0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:17,028][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0ba0946f50>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/chengr_lab/cse12132340/jaxrl-baselines/cleanrl-blines/train.py", line 25, in test_main
    dqn(config)
  File "/home/chengr_lab/cse12132340/jaxrl-baselines/cleanrl-blines/agent/dqn.py", line 71, in main
    wandb.init(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1178, in init
    wandb._sentry.reraise(e)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 627, in init
    run = Run(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 594, in __init__
    self._init(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 709, in _init
    self._config._update(config, ignore_locked=True)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 177, in _update
    sanitized = self._sanitize_dict(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 264, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 282, in _sanitize
    val = json_friendly_val(val)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/util.py", line 671, in json_friendly_val
    converted = asdict(val)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1238, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1245, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1275, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: first argument must be callable or None

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2024-05-22 15:47:19,069][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0c868fcf70>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:19,070][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0c868fd0f0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:19,071][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0c868fdea0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:19,073][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0c868fc610>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:19,074][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0c868fd210>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:19,074][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0c868fe1d0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
exp_name: ddpg-Hopper-v4
seed: 42
track: true
wandb_project_name: JAXRL-baselines
wandb_entity: sustech-emi-org
capture_video: false
save_model: false
upload_model: false
hf_entity: ''
agent: ddpg
env_id: Hopper-v4
env_name: hopper
total_timesteps: 1000000
learning_rate: 0.0003
buffer_size: 1000000
gamma: 0.99
tau: 0.005
batch_size: 256
exploration_noise: 0.1
learning_starts: 25000
policy_frequency: 2
noise_clip: 0.5
num_envs: 1

random seed=42
[2024-05-22 15:47:25,116][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0d97a70460>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:25,117][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0d97a70c40>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:25,118][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0d97a70910>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:25,120][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0d97a72980>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:25,120][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0d97a72b00>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:25,121][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0d97a72cb0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/chengr_lab/cse12132340/jaxrl-baselines/cleanrl-blines/train.py", line 29, in test_main
    ddpg(config)
  File "/home/chengr_lab/cse12132340/jaxrl-baselines/cleanrl-blines/agent/ddpg.py", line 81, in main
    wandb.init(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1178, in init
    wandb._sentry.reraise(e)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 627, in init
    run = Run(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 594, in __init__
    self._init(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 709, in _init
    self._config._update(config, ignore_locked=True)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 177, in _update
    sanitized = self._sanitize_dict(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 264, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 282, in _sanitize
    val = json_friendly_val(val)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/util.py", line 671, in json_friendly_val
    converted = asdict(val)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1238, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1245, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1275, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: first argument must be callable or None

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2024-05-22 15:47:27,184][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0e7d9dcf70>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:27,185][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0e7d9dd0f0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:27,186][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0e7d9ddea0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:27,188][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0e7d9dc610>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:27,189][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0e7d9dd210>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:27,190][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0e7d9de200>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
exp_name: td3-Hopper-v4
seed: 1024
track: true
wandb_project_name: JAXRL-baselines
wandb_entity: sustech-emi-org
capture_video: false
save_model: false
upload_model: false
hf_entity: ''
agent: td3
env_id: Hopper-v4
env_name: hopper
total_timesteps: 1000000
learning_rate: 0.0003
buffer_size: 1000000
gamma: 0.99
tau: 0.005
batch_size: 256
policy_noise: 0.2
exploration_noise: 0.1
learning_starts: 25000
policy_frequency: 2
noise_clip: 0.5
num_envs: 1

random seed=42
[2024-05-22 15:47:32,625][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f44400bc400>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:32,626][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f44400bcb80>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:32,627][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f44400bcac0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:32,628][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f44400beb90>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:32,629][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f44400bed10>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:32,630][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f44400beec0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/chengr_lab/cse12132340/jaxrl-baselines/cleanrl-blines/train.py", line 27, in test_main
    td3(config)
  File "/home/chengr_lab/cse12132340/jaxrl-baselines/cleanrl-blines/agent/td3.py", line 80, in main
    wandb.init(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1178, in init
    wandb._sentry.reraise(e)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 627, in init
    run = Run(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 594, in __init__
    self._init(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 709, in _init
    self._config._update(config, ignore_locked=True)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 177, in _update
    sanitized = self._sanitize_dict(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 264, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 282, in _sanitize
    val = json_friendly_val(val)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/util.py", line 671, in json_friendly_val
    converted = asdict(val)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1238, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1245, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1275, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: first argument must be callable or None

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2024-05-22 15:47:34,700][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4526064f70>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:34,702][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f45260650f0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:34,703][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4526065ea0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:34,705][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4526064610>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:34,706][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4526065210>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:34,707][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f45260661d0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
exp_name: c51-CartPole-v1
seed: 1
track: true
wandb_project_name: JAXRL-baselines
wandb_entity: sustech-emi-org
capture_video: false
save_model: false
upload_model: false
hf_entity: ''
agent: c51
env_id: CartPole-v1
total_timesteps: 500000
learning_rate: 0.00025
num_envs: 1
n_atoms: 101
v_min: -100
v_max: 100
buffer_size: 10000
gamma: 0.99
target_network_frequency: 500
batch_size: 128
start_e: 1
end_e: 0.05
exploration_fraction: 0.5
learning_starts: 10000
train_frequency: 10

random seed=42
[2024-05-22 15:47:40,177][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4d418ac790>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:40,178][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4d418acf10>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:40,179][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4d418ace50>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:40,180][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4d418aef20>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:40,181][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4d418af0a0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:40,182][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4d418af250>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/chengr_lab/cse12132340/jaxrl-baselines/cleanrl-blines/train.py", line 31, in test_main
    c51(config)
  File "/home/chengr_lab/cse12132340/jaxrl-baselines/cleanrl-blines/agent/c51.py", line 77, in main
    wandb.init(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1178, in init
    wandb._sentry.reraise(e)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 627, in init
    run = Run(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 594, in __init__
    self._init(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 709, in _init
    self._config._update(config, ignore_locked=True)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 177, in _update
    sanitized = self._sanitize_dict(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 264, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 282, in _sanitize
    val = json_friendly_val(val)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/util.py", line 671, in json_friendly_val
    converted = asdict(val)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1238, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1245, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1275, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: first argument must be callable or None

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2024-05-22 15:47:42,245][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4e27858f70>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:42,246][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4e278590f0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:42,247][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4e27859ea0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:42,249][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4e27858610>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:42,249][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4e27859210>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:47:42,250][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4e2785a1d0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
