exp_name: dqn-CartPole-v1
seed: 31415
track: true
wandb_project_name: JAXRL-baselines
wandb_entity: sustech-emi-org
capture_video: false
save_model: false
upload_model: false
hf_entity: ''
agent: dqn
env_id: CartPole-v1
total_timesteps: 500000
learning_rate: 0.00025
num_envs: 1
buffer_size: 10000
gamma: 0.99
tau: 1.0
target_network_frequency: 500
batch_size: 128
start_e: 1.0
end_e: 0.05
exploration_fraction: 0.5
learning_starts: 10000
train_frequency: 10

random seed=42
[2024-05-22 15:58:51,953][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f78530f4580>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:58:51,954][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f78530f4f40>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:58:51,955][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f78530f4d00>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:58:51,956][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f78530f6d70>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:58:51,957][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f78530f6ef0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:58:51,957][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f78530f70a0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/chengr_lab/cse12132340/jaxrl-baselines/cleanrl-blines/train.py", line 73, in <module>
    test_main()
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/chengr_lab/cse12132340/jaxrl-baselines/cleanrl-blines/train.py", line 26, in test_main
    dqn(config)
  File "/home/chengr_lab/cse12132340/jaxrl-baselines/cleanrl-blines/agent/dqn.py", line 71, in main
    wandb.init(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1178, in init
    wandb._sentry.reraise(e)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 627, in init
    run = Run(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 594, in __init__
    self._init(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 709, in _init
    self._config._update(config, ignore_locked=True)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 177, in _update
    sanitized = self._sanitize_dict(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 264, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 282, in _sanitize
    val = json_friendly_val(val)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/util.py", line 671, in json_friendly_val
    converted = asdict(val)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1238, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1245, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1275, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: first argument must be callable or None
[2024-05-22 15:58:53,995][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f7939065180>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:58:53,997][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f7939065f00>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:58:53,998][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f7939066110>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:58:54,000][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f7939067fd0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:58:54,001][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f7939064e80>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:58:54,002][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f79390650f0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
exp_name: ddpg-Hopper-v4
seed: 42
track: true
wandb_project_name: JAXRL-baselines
wandb_entity: sustech-emi-org
capture_video: false
save_model: false
upload_model: false
hf_entity: ''
agent: ddpg
env_id: Hopper-v4
env_name: hopper
total_timesteps: 1000000
learning_rate: 0.0003
buffer_size: 1000000
gamma: 0.99
tau: 0.005
batch_size: 256
exploration_noise: 0.1
learning_starts: 25000
policy_frequency: 2
noise_clip: 0.5
num_envs: 1

random seed=42
[2024-05-22 15:59:00,073][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1bb510c460>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:00,074][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1bb510cc10>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:00,075][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1bb510cac0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:00,076][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1bb510ea40>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:00,077][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1bb510ebc0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:00,077][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1bb510ed70>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/chengr_lab/cse12132340/jaxrl-baselines/cleanrl-blines/train.py", line 73, in <module>
    test_main()
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/chengr_lab/cse12132340/jaxrl-baselines/cleanrl-blines/train.py", line 30, in test_main
    ddpg(config)
  File "/home/chengr_lab/cse12132340/jaxrl-baselines/cleanrl-blines/agent/ddpg.py", line 81, in main
    wandb.init(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1178, in init
    wandb._sentry.reraise(e)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 627, in init
    run = Run(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 594, in __init__
    self._init(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 709, in _init
    self._config._update(config, ignore_locked=True)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 177, in _update
    sanitized = self._sanitize_dict(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 264, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 282, in _sanitize
    val = json_friendly_val(val)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/util.py", line 671, in json_friendly_val
    converted = asdict(val)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1238, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1245, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1275, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: first argument must be callable or None
[2024-05-22 15:59:02,148][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1c9b08d120>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:02,150][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1c9b08dea0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:02,151][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1c9b08e0b0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:02,152][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1c9b08ff70>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:02,154][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1c9b08ce50>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:02,154][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1c9b08d0f0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
exp_name: td3-Hopper-v4
seed: 1024
track: true
wandb_project_name: JAXRL-baselines
wandb_entity: sustech-emi-org
capture_video: false
save_model: false
upload_model: false
hf_entity: ''
agent: td3
env_id: Hopper-v4
env_name: hopper
total_timesteps: 1000000
learning_rate: 0.0003
buffer_size: 1000000
gamma: 0.99
tau: 0.005
batch_size: 256
policy_noise: 0.2
exploration_noise: 0.1
learning_starts: 25000
policy_frequency: 2
noise_clip: 0.5
num_envs: 1

random seed=42
[2024-05-22 15:59:07,760][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe151188460>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:07,760][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe151188be0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:07,761][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe151188b20>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:07,763][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe15118abf0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:07,763][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe15118ad70>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:07,764][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe15118af20>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/chengr_lab/cse12132340/jaxrl-baselines/cleanrl-blines/train.py", line 73, in <module>
    test_main()
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/chengr_lab/cse12132340/jaxrl-baselines/cleanrl-blines/train.py", line 28, in test_main
    td3(config)
  File "/home/chengr_lab/cse12132340/jaxrl-baselines/cleanrl-blines/agent/td3.py", line 80, in main
    wandb.init(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1178, in init
    wandb._sentry.reraise(e)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 627, in init
    run = Run(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 594, in __init__
    self._init(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 709, in _init
    self._config._update(config, ignore_locked=True)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 177, in _update
    sanitized = self._sanitize_dict(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 264, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 282, in _sanitize
    val = json_friendly_val(val)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/util.py", line 671, in json_friendly_val
    converted = asdict(val)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1238, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1245, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1275, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: first argument must be callable or None
[2024-05-22 15:59:09,830][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe237135180>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:09,831][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe237135f00>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:09,831][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe237136110>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:09,833][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe237137fd0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:09,834][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe237134e80>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:09,835][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe2371350f0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
exp_name: c51-CartPole-v1
seed: 1
track: true
wandb_project_name: JAXRL-baselines
wandb_entity: sustech-emi-org
capture_video: false
save_model: false
upload_model: false
hf_entity: ''
agent: c51
env_id: CartPole-v1
total_timesteps: 500000
learning_rate: 0.00025
num_envs: 1
n_atoms: 101
v_min: -100
v_max: 100
buffer_size: 10000
gamma: 0.99
target_network_frequency: 500
batch_size: 128
start_e: 1
end_e: 0.05
exploration_fraction: 0.5
learning_starts: 10000
train_frequency: 10

random seed=42
[2024-05-22 15:59:15,070][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f02884f09a0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:15,071][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f02884f1120>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:15,072][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f02884f1060>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:15,074][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f02884f3130>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:15,075][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f02884f32b0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:15,075][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f02884f3460>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/chengr_lab/cse12132340/jaxrl-baselines/cleanrl-blines/train.py", line 73, in <module>
    test_main()
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/chengr_lab/cse12132340/jaxrl-baselines/cleanrl-blines/train.py", line 32, in test_main
    c51(config)
  File "/home/chengr_lab/cse12132340/jaxrl-baselines/cleanrl-blines/agent/c51.py", line 77, in main
    wandb.init(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1178, in init
    wandb._sentry.reraise(e)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 627, in init
    run = Run(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 594, in __init__
    self._init(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 709, in _init
    self._config._update(config, ignore_locked=True)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 177, in _update
    sanitized = self._sanitize_dict(
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 264, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 282, in _sanitize
    val = json_friendly_val(val)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/site-packages/wandb/util.py", line 671, in json_friendly_val
    converted = asdict(val)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1238, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1245, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/home/chengr_lab/cse12132340/miniconda3/envs/jaxrl-baselines/lib/python3.10/dataclasses.py", line 1275, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: first argument must be callable or None
[2024-05-22 15:59:17,142][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f036e499180>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:17,143][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f036e499f00>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:17,144][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f036e49a110>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:17,146][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f036e49bfd0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:17,147][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f036e498e80>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
[2024-05-22 15:59:17,147][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f036e4990f0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno -2] Name or service not known)")': /api/4504800232407040/envelope/
